#############################################################################
# Makefile for building: cs8Tools
# Generated by qmake (3.0) (Qt 5.7.1)
# Project:  cs8Tools.pro
# Template: subdirs
# Command: D:\Qt\5.7\msvc2015\bin\qmake.exe -spec win32-msvc2015 -o Makefile cs8Tools.pro
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = D:\Qt\5.7\msvc2015\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		sub-version \
		sub-cs8Backup \
		sub-cs8BackupSync \
		sub-cs8LogFileViewer \
		sub-installer


sub-version-qmake_all:  FORCE
	@if not exist version\ mkdir version\ & if not exist version\ exit 1
	cd version\ && $(QMAKE) D:\data\Cpp\_SAXESwissSystem\cs8Tools\version\version.pro -spec win32-msvc2015 -o Makefile
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd version\ && $(MAKE) -f Makefile qmake_all
sub-version: FORCE
	@if not exist version\ mkdir version\ & if not exist version\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd version\ && ( if not exist Makefile $(QMAKE) D:\data\Cpp\_SAXESwissSystem\cs8Tools\version\version.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile
sub-version-make_first: FORCE
	@if not exist version\ mkdir version\ & if not exist version\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd version\ && ( if not exist Makefile $(QMAKE) D:\data\Cpp\_SAXESwissSystem\cs8Tools\version\version.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile 
sub-version-all: FORCE
	@if not exist version\ mkdir version\ & if not exist version\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd version\ && ( if not exist Makefile $(QMAKE) D:\data\Cpp\_SAXESwissSystem\cs8Tools\version\version.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile all
sub-version-clean: FORCE
	@if not exist version\ mkdir version\ & if not exist version\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd version\ && ( if not exist Makefile $(QMAKE) D:\data\Cpp\_SAXESwissSystem\cs8Tools\version\version.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile clean
sub-version-distclean: FORCE
	@if not exist version\ mkdir version\ & if not exist version\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd version\ && ( if not exist Makefile $(QMAKE) D:\data\Cpp\_SAXESwissSystem\cs8Tools\version\version.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile distclean
sub-version-install_subtargets: FORCE
	@if not exist version\ mkdir version\ & if not exist version\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd version\ && ( if not exist Makefile $(QMAKE) D:\data\Cpp\_SAXESwissSystem\cs8Tools\version\version.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile install
sub-version-uninstall_subtargets: FORCE
	@if not exist version\ mkdir version\ & if not exist version\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd version\ && ( if not exist Makefile $(QMAKE) D:\data\Cpp\_SAXESwissSystem\cs8Tools\version\version.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-cs8Backup-qmake_all:  FORCE
	@if not exist cs8Backup\ mkdir cs8Backup\ & if not exist cs8Backup\ exit 1
	cd cs8Backup\ && $(QMAKE) D:\data\Cpp\_SAXESwissSystem\cs8Tools\cs8Backup\cs8Backup.pro -spec win32-msvc2015 -o Makefile
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd cs8Backup\ && $(MAKE) -f Makefile qmake_all
sub-cs8Backup: FORCE
	@if not exist cs8Backup\ mkdir cs8Backup\ & if not exist cs8Backup\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd cs8Backup\ && ( if not exist Makefile $(QMAKE) D:\data\Cpp\_SAXESwissSystem\cs8Tools\cs8Backup\cs8Backup.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile
sub-cs8Backup-make_first: FORCE
	@if not exist cs8Backup\ mkdir cs8Backup\ & if not exist cs8Backup\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd cs8Backup\ && ( if not exist Makefile $(QMAKE) D:\data\Cpp\_SAXESwissSystem\cs8Tools\cs8Backup\cs8Backup.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile 
sub-cs8Backup-all: FORCE
	@if not exist cs8Backup\ mkdir cs8Backup\ & if not exist cs8Backup\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd cs8Backup\ && ( if not exist Makefile $(QMAKE) D:\data\Cpp\_SAXESwissSystem\cs8Tools\cs8Backup\cs8Backup.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile all
sub-cs8Backup-clean: FORCE
	@if not exist cs8Backup\ mkdir cs8Backup\ & if not exist cs8Backup\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd cs8Backup\ && ( if not exist Makefile $(QMAKE) D:\data\Cpp\_SAXESwissSystem\cs8Tools\cs8Backup\cs8Backup.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile clean
sub-cs8Backup-distclean: FORCE
	@if not exist cs8Backup\ mkdir cs8Backup\ & if not exist cs8Backup\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd cs8Backup\ && ( if not exist Makefile $(QMAKE) D:\data\Cpp\_SAXESwissSystem\cs8Tools\cs8Backup\cs8Backup.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile distclean
sub-cs8Backup-install_subtargets: FORCE
	@if not exist cs8Backup\ mkdir cs8Backup\ & if not exist cs8Backup\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd cs8Backup\ && ( if not exist Makefile $(QMAKE) D:\data\Cpp\_SAXESwissSystem\cs8Tools\cs8Backup\cs8Backup.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile install
sub-cs8Backup-uninstall_subtargets: FORCE
	@if not exist cs8Backup\ mkdir cs8Backup\ & if not exist cs8Backup\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd cs8Backup\ && ( if not exist Makefile $(QMAKE) D:\data\Cpp\_SAXESwissSystem\cs8Tools\cs8Backup\cs8Backup.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-cs8BackupSync-qmake_all:  FORCE
	@if not exist cs8BackupSync\ mkdir cs8BackupSync\ & if not exist cs8BackupSync\ exit 1
	cd cs8BackupSync\ && $(QMAKE) D:\data\Cpp\_SAXESwissSystem\cs8Tools\cs8BackupSync\cs8BackupSync.pro -spec win32-msvc2015 -o Makefile
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd cs8BackupSync\ && $(MAKE) -f Makefile qmake_all
sub-cs8BackupSync: FORCE
	@if not exist cs8BackupSync\ mkdir cs8BackupSync\ & if not exist cs8BackupSync\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd cs8BackupSync\ && ( if not exist Makefile $(QMAKE) D:\data\Cpp\_SAXESwissSystem\cs8Tools\cs8BackupSync\cs8BackupSync.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile
sub-cs8BackupSync-make_first: FORCE
	@if not exist cs8BackupSync\ mkdir cs8BackupSync\ & if not exist cs8BackupSync\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd cs8BackupSync\ && ( if not exist Makefile $(QMAKE) D:\data\Cpp\_SAXESwissSystem\cs8Tools\cs8BackupSync\cs8BackupSync.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile 
sub-cs8BackupSync-all: FORCE
	@if not exist cs8BackupSync\ mkdir cs8BackupSync\ & if not exist cs8BackupSync\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd cs8BackupSync\ && ( if not exist Makefile $(QMAKE) D:\data\Cpp\_SAXESwissSystem\cs8Tools\cs8BackupSync\cs8BackupSync.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile all
sub-cs8BackupSync-clean: FORCE
	@if not exist cs8BackupSync\ mkdir cs8BackupSync\ & if not exist cs8BackupSync\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd cs8BackupSync\ && ( if not exist Makefile $(QMAKE) D:\data\Cpp\_SAXESwissSystem\cs8Tools\cs8BackupSync\cs8BackupSync.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile clean
sub-cs8BackupSync-distclean: FORCE
	@if not exist cs8BackupSync\ mkdir cs8BackupSync\ & if not exist cs8BackupSync\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd cs8BackupSync\ && ( if not exist Makefile $(QMAKE) D:\data\Cpp\_SAXESwissSystem\cs8Tools\cs8BackupSync\cs8BackupSync.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile distclean
sub-cs8BackupSync-install_subtargets: FORCE
	@if not exist cs8BackupSync\ mkdir cs8BackupSync\ & if not exist cs8BackupSync\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd cs8BackupSync\ && ( if not exist Makefile $(QMAKE) D:\data\Cpp\_SAXESwissSystem\cs8Tools\cs8BackupSync\cs8BackupSync.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile install
sub-cs8BackupSync-uninstall_subtargets: FORCE
	@if not exist cs8BackupSync\ mkdir cs8BackupSync\ & if not exist cs8BackupSync\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd cs8BackupSync\ && ( if not exist Makefile $(QMAKE) D:\data\Cpp\_SAXESwissSystem\cs8Tools\cs8BackupSync\cs8BackupSync.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-cs8LogFileViewer-qmake_all:  FORCE
	@if not exist cs8LogFileViewer\ mkdir cs8LogFileViewer\ & if not exist cs8LogFileViewer\ exit 1
	cd cs8LogFileViewer\ && $(QMAKE) D:\data\Cpp\_SAXESwissSystem\cs8Tools\cs8LogFileViewer\cs8LogFileViewer.pro -spec win32-msvc2015 -o Makefile
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd cs8LogFileViewer\ && $(MAKE) -f Makefile qmake_all
sub-cs8LogFileViewer: FORCE
	@if not exist cs8LogFileViewer\ mkdir cs8LogFileViewer\ & if not exist cs8LogFileViewer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd cs8LogFileViewer\ && ( if not exist Makefile $(QMAKE) D:\data\Cpp\_SAXESwissSystem\cs8Tools\cs8LogFileViewer\cs8LogFileViewer.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile
sub-cs8LogFileViewer-make_first: FORCE
	@if not exist cs8LogFileViewer\ mkdir cs8LogFileViewer\ & if not exist cs8LogFileViewer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd cs8LogFileViewer\ && ( if not exist Makefile $(QMAKE) D:\data\Cpp\_SAXESwissSystem\cs8Tools\cs8LogFileViewer\cs8LogFileViewer.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile 
sub-cs8LogFileViewer-all: FORCE
	@if not exist cs8LogFileViewer\ mkdir cs8LogFileViewer\ & if not exist cs8LogFileViewer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd cs8LogFileViewer\ && ( if not exist Makefile $(QMAKE) D:\data\Cpp\_SAXESwissSystem\cs8Tools\cs8LogFileViewer\cs8LogFileViewer.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile all
sub-cs8LogFileViewer-clean: FORCE
	@if not exist cs8LogFileViewer\ mkdir cs8LogFileViewer\ & if not exist cs8LogFileViewer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd cs8LogFileViewer\ && ( if not exist Makefile $(QMAKE) D:\data\Cpp\_SAXESwissSystem\cs8Tools\cs8LogFileViewer\cs8LogFileViewer.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile clean
sub-cs8LogFileViewer-distclean: FORCE
	@if not exist cs8LogFileViewer\ mkdir cs8LogFileViewer\ & if not exist cs8LogFileViewer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd cs8LogFileViewer\ && ( if not exist Makefile $(QMAKE) D:\data\Cpp\_SAXESwissSystem\cs8Tools\cs8LogFileViewer\cs8LogFileViewer.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile distclean
sub-cs8LogFileViewer-install_subtargets: FORCE
	@if not exist cs8LogFileViewer\ mkdir cs8LogFileViewer\ & if not exist cs8LogFileViewer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd cs8LogFileViewer\ && ( if not exist Makefile $(QMAKE) D:\data\Cpp\_SAXESwissSystem\cs8Tools\cs8LogFileViewer\cs8LogFileViewer.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile install
sub-cs8LogFileViewer-uninstall_subtargets: FORCE
	@if not exist cs8LogFileViewer\ mkdir cs8LogFileViewer\ & if not exist cs8LogFileViewer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd cs8LogFileViewer\ && ( if not exist Makefile $(QMAKE) D:\data\Cpp\_SAXESwissSystem\cs8Tools\cs8LogFileViewer\cs8LogFileViewer.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-installer-qmake_all: sub-cs8Backup-qmake_all sub-cs8BackupSync-qmake_all sub-cs8LogFileViewer-qmake_all FORCE
	@if not exist installer\ mkdir installer\ & if not exist installer\ exit 1
	cd installer\ && $(QMAKE) D:\data\Cpp\_SAXESwissSystem\cs8Tools\installer\installer.pro -spec win32-msvc2015 -o Makefile
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd installer\ && $(MAKE) -f Makefile qmake_all
sub-installer: sub-cs8Backup \
		sub-cs8BackupSync \
		sub-cs8LogFileViewer FORCE
	@if not exist installer\ mkdir installer\ & if not exist installer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd installer\ && ( if not exist Makefile $(QMAKE) D:\data\Cpp\_SAXESwissSystem\cs8Tools\installer\installer.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile
sub-installer-make_first: sub-cs8Backup-make_first sub-cs8BackupSync-make_first sub-cs8LogFileViewer-make_first FORCE
	@if not exist installer\ mkdir installer\ & if not exist installer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd installer\ && ( if not exist Makefile $(QMAKE) D:\data\Cpp\_SAXESwissSystem\cs8Tools\installer\installer.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile 
sub-installer-all: sub-cs8Backup-all sub-cs8BackupSync-all sub-cs8LogFileViewer-all FORCE
	@if not exist installer\ mkdir installer\ & if not exist installer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd installer\ && ( if not exist Makefile $(QMAKE) D:\data\Cpp\_SAXESwissSystem\cs8Tools\installer\installer.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile all
sub-installer-clean: sub-cs8Backup-clean sub-cs8BackupSync-clean sub-cs8LogFileViewer-clean FORCE
	@if not exist installer\ mkdir installer\ & if not exist installer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd installer\ && ( if not exist Makefile $(QMAKE) D:\data\Cpp\_SAXESwissSystem\cs8Tools\installer\installer.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile clean
sub-installer-distclean: sub-cs8Backup-distclean sub-cs8BackupSync-distclean sub-cs8LogFileViewer-distclean FORCE
	@if not exist installer\ mkdir installer\ & if not exist installer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd installer\ && ( if not exist Makefile $(QMAKE) D:\data\Cpp\_SAXESwissSystem\cs8Tools\installer\installer.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile distclean
sub-installer-install_subtargets: sub-cs8Backup-install_subtargets sub-cs8BackupSync-install_subtargets sub-cs8LogFileViewer-install_subtargets FORCE
	@if not exist installer\ mkdir installer\ & if not exist installer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd installer\ && ( if not exist Makefile $(QMAKE) D:\data\Cpp\_SAXESwissSystem\cs8Tools\installer\installer.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile install
sub-installer-uninstall_subtargets: sub-cs8Backup-uninstall_subtargets sub-cs8BackupSync-uninstall_subtargets sub-cs8LogFileViewer-uninstall_subtargets FORCE
	@if not exist installer\ mkdir installer\ & if not exist installer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd installer\ && ( if not exist Makefile $(QMAKE) D:\data\Cpp\_SAXESwissSystem\cs8Tools\installer\installer.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile uninstall

Makefile: cs8Tools.pro ..\..\..\..\Qt\5.7\msvc2015\mkspecs\win32-msvc2015\qmake.conf ..\..\..\..\Qt\5.7\msvc2015\mkspecs\features\spec_pre.prf \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\common\angle.conf \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\common\msvc-base.conf \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\common\msvc-desktop.conf \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\qconfig.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_3dcore.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_3dcore_private.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_3dextras.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_3dextras_private.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_3dinput.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_3dinput_private.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_3dlogic.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_3dlogic_private.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_3dquick.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_3dquick_private.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_3dquickextras.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_3dquickextras_private.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_3dquickinput.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_3dquickinput_private.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_3dquickrender.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_3dquickrender_private.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_3drender.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_3drender_private.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_axbase.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_axbase_private.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_axcontainer.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_axcontainer_private.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_axserver.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_axserver_private.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_bluetooth.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_bluetooth_private.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_bootstrap_private.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_charts.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_charts_private.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_clucene_private.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_concurrent.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_concurrent_private.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_core.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_core_private.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_datavisualization.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_datavisualization_private.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_dbus.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_dbus_private.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_designer.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_designer_private.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_designercomponents_private.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_gamepad.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_gamepad_private.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_gui.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_gui_private.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_help.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_help_private.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_location.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_location_private.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_multimedia.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_multimedia_private.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_multimediawidgets.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_multimediawidgets_private.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_network.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_network_private.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_nfc.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_nfc_private.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_opengl.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_opengl_private.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_openglextensions.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_openglextensions_private.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_packetprotocol_private.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_platformsupport_private.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_positioning.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_positioning_private.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_printsupport.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_printsupport_private.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_qml.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_qml_private.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_qmldebug_private.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_qmldevtools_private.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_qmltest.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_qmltest_private.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_quick.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_quick_private.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_quickcontrols2.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_quickcontrols2_private.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_quickparticles_private.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_quicktemplates2_private.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_quickwidgets.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_quickwidgets_private.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_sensors.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_sensors_private.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_serialbus.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_serialbus_private.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_serialport.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_serialport_private.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_sql.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_sql_private.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_svg.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_svg_private.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_testlib.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_testlib_private.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_uiplugin.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_uitools.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_uitools_private.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_webchannel.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_webchannel_private.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_webengine.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_webengine_private.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_webenginecore.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_webenginecore_private.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_webenginecoreheaders_private.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_webenginewidgets.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_webenginewidgets_private.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_websockets.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_websockets_private.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_webview.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_webview_private.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_widgets.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_widgets_private.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_winextras.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_winextras_private.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_xml.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_xml_private.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_xmlpatterns.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_xmlpatterns_private.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_zlib_private.pri \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\features\qt_functions.prf \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\features\qt_config.prf \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\features\win32\qt_config.prf \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\win32-msvc2015\qmake.conf \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\features\spec_post.prf \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\features\exclusive_builds.prf \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\features\toolchain.prf \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\features\default_pre.prf \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\features\win32\default_pre.prf \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\features\resolve_config.prf \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\features\exclusive_builds_post.prf \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\features\default_post.prf \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\features\win32\rtti.prf \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\features\precompile_header.prf \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\features\warn_on.prf \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\features\file_copies.prf \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\features\win32\windows.prf \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\features\testcase_targets.prf \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\features\exceptions.prf \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\features\yacc.prf \
		..\..\..\..\Qt\5.7\msvc2015\mkspecs\features\lex.prf \
		cs8Tools.pro
	$(QMAKE) -spec win32-msvc2015 -o Makefile cs8Tools.pro
..\..\..\..\Qt\5.7\msvc2015\mkspecs\features\spec_pre.prf:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\common\angle.conf:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\common\msvc-base.conf:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\common\msvc-desktop.conf:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\qconfig.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_3dcore.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_3dcore_private.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_3dextras.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_3dextras_private.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_3dinput.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_3dinput_private.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_3dlogic.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_3dlogic_private.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_3dquick.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_3dquick_private.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_3dquickextras.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_3dquickextras_private.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_3dquickinput.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_3dquickinput_private.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_3dquickrender.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_3dquickrender_private.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_3drender.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_3drender_private.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_axbase.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_axbase_private.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_axcontainer.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_axcontainer_private.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_axserver.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_axserver_private.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_bluetooth.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_bluetooth_private.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_bootstrap_private.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_charts.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_charts_private.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_clucene_private.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_concurrent.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_concurrent_private.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_core.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_core_private.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_datavisualization.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_datavisualization_private.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_dbus.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_dbus_private.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_designer.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_designer_private.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_designercomponents_private.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_gamepad.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_gamepad_private.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_gui.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_gui_private.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_help.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_help_private.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_location.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_location_private.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_multimedia.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_multimedia_private.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_multimediawidgets.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_network.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_network_private.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_nfc.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_nfc_private.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_opengl.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_opengl_private.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_openglextensions.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_openglextensions_private.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_packetprotocol_private.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_platformsupport_private.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_positioning.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_positioning_private.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_printsupport.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_printsupport_private.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_qml.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_qml_private.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_qmldebug_private.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_qmldevtools_private.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_qmltest.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_qmltest_private.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_quick.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_quick_private.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_quickcontrols2.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_quickcontrols2_private.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_quickparticles_private.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_quicktemplates2_private.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_quickwidgets.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_quickwidgets_private.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_sensors.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_sensors_private.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_serialbus.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_serialbus_private.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_serialport.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_serialport_private.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_sql.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_sql_private.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_svg.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_svg_private.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_testlib.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_testlib_private.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_uiplugin.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_uitools.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_uitools_private.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_webchannel.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_webchannel_private.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_webengine.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_webengine_private.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_webenginecore.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_webenginecore_private.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_webenginecoreheaders_private.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_webenginewidgets.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_webenginewidgets_private.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_websockets.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_websockets_private.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_webview.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_webview_private.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_widgets.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_widgets_private.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_winextras.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_winextras_private.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_xml.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_xml_private.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_xmlpatterns.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_xmlpatterns_private.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\modules\qt_lib_zlib_private.pri:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\features\qt_functions.prf:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\features\qt_config.prf:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\features\win32\qt_config.prf:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\win32-msvc2015\qmake.conf:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\features\spec_post.prf:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\features\exclusive_builds.prf:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\features\toolchain.prf:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\features\default_pre.prf:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\features\win32\default_pre.prf:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\features\resolve_config.prf:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\features\exclusive_builds_post.prf:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\features\default_post.prf:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\features\win32\rtti.prf:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\features\precompile_header.prf:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\features\warn_on.prf:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\features\file_copies.prf:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\features\win32\windows.prf:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\features\testcase_targets.prf:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\features\exceptions.prf:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\features\yacc.prf:
..\..\..\..\Qt\5.7\msvc2015\mkspecs\features\lex.prf:
cs8Tools.pro:
qmake: FORCE
	@$(QMAKE) -spec win32-msvc2015 -o Makefile cs8Tools.pro

qmake_all: sub-version-qmake_all sub-cs8Backup-qmake_all sub-cs8BackupSync-qmake_all sub-cs8LogFileViewer-qmake_all sub-installer-qmake_all FORCE

make_first: sub-version-make_first sub-cs8Backup-make_first sub-cs8BackupSync-make_first sub-cs8LogFileViewer-make_first sub-installer-make_first  FORCE
all: sub-version-all sub-cs8Backup-all sub-cs8BackupSync-all sub-cs8LogFileViewer-all sub-installer-all  FORCE
clean: sub-version-clean sub-cs8Backup-clean sub-cs8BackupSync-clean sub-cs8LogFileViewer-clean sub-installer-clean  FORCE
distclean: sub-version-distclean sub-cs8Backup-distclean sub-cs8BackupSync-distclean sub-cs8LogFileViewer-distclean sub-installer-distclean  FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-version-install_subtargets sub-cs8Backup-install_subtargets sub-cs8BackupSync-install_subtargets sub-cs8LogFileViewer-install_subtargets sub-installer-install_subtargets FORCE
uninstall_subtargets: sub-version-uninstall_subtargets sub-cs8Backup-uninstall_subtargets sub-cs8BackupSync-uninstall_subtargets sub-cs8LogFileViewer-uninstall_subtargets sub-installer-uninstall_subtargets FORCE

sub-version-debug:
	@if not exist version\ mkdir version\ & if not exist version\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd version\ && ( if not exist Makefile $(QMAKE) D:\data\Cpp\_SAXESwissSystem\cs8Tools\version\version.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile debug
sub-cs8Backup-debug:
	@if not exist cs8Backup\ mkdir cs8Backup\ & if not exist cs8Backup\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd cs8Backup\ && ( if not exist Makefile $(QMAKE) D:\data\Cpp\_SAXESwissSystem\cs8Tools\cs8Backup\cs8Backup.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile debug
sub-cs8BackupSync-debug:
	@if not exist cs8BackupSync\ mkdir cs8BackupSync\ & if not exist cs8BackupSync\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd cs8BackupSync\ && ( if not exist Makefile $(QMAKE) D:\data\Cpp\_SAXESwissSystem\cs8Tools\cs8BackupSync\cs8BackupSync.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile debug
sub-cs8LogFileViewer-debug:
	@if not exist cs8LogFileViewer\ mkdir cs8LogFileViewer\ & if not exist cs8LogFileViewer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd cs8LogFileViewer\ && ( if not exist Makefile $(QMAKE) D:\data\Cpp\_SAXESwissSystem\cs8Tools\cs8LogFileViewer\cs8LogFileViewer.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile debug
sub-installer-debug: sub-cs8Backup-debug sub-cs8BackupSync-debug sub-cs8LogFileViewer-debug
	@if not exist installer\ mkdir installer\ & if not exist installer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd installer\ && ( if not exist Makefile $(QMAKE) D:\data\Cpp\_SAXESwissSystem\cs8Tools\installer\installer.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile debug
debug: sub-version-debug sub-cs8Backup-debug sub-cs8BackupSync-debug sub-cs8LogFileViewer-debug sub-installer-debug

sub-version-release:
	@if not exist version\ mkdir version\ & if not exist version\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd version\ && ( if not exist Makefile $(QMAKE) D:\data\Cpp\_SAXESwissSystem\cs8Tools\version\version.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile release
sub-cs8Backup-release:
	@if not exist cs8Backup\ mkdir cs8Backup\ & if not exist cs8Backup\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd cs8Backup\ && ( if not exist Makefile $(QMAKE) D:\data\Cpp\_SAXESwissSystem\cs8Tools\cs8Backup\cs8Backup.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile release
sub-cs8BackupSync-release:
	@if not exist cs8BackupSync\ mkdir cs8BackupSync\ & if not exist cs8BackupSync\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd cs8BackupSync\ && ( if not exist Makefile $(QMAKE) D:\data\Cpp\_SAXESwissSystem\cs8Tools\cs8BackupSync\cs8BackupSync.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile release
sub-cs8LogFileViewer-release:
	@if not exist cs8LogFileViewer\ mkdir cs8LogFileViewer\ & if not exist cs8LogFileViewer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd cs8LogFileViewer\ && ( if not exist Makefile $(QMAKE) D:\data\Cpp\_SAXESwissSystem\cs8Tools\cs8LogFileViewer\cs8LogFileViewer.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile release
sub-installer-release: sub-cs8Backup-release sub-cs8BackupSync-release sub-cs8LogFileViewer-release
	@if not exist installer\ mkdir installer\ & if not exist installer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd installer\ && ( if not exist Makefile $(QMAKE) D:\data\Cpp\_SAXESwissSystem\cs8Tools\installer\installer.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile release
release: sub-version-release sub-cs8Backup-release sub-cs8BackupSync-release sub-cs8LogFileViewer-release sub-installer-release

sub-version-check:
	@if not exist version\ mkdir version\ & if not exist version\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd version\ && ( if not exist Makefile $(QMAKE) D:\data\Cpp\_SAXESwissSystem\cs8Tools\version\version.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile check
sub-cs8Backup-check:
	@if not exist cs8Backup\ mkdir cs8Backup\ & if not exist cs8Backup\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd cs8Backup\ && ( if not exist Makefile $(QMAKE) D:\data\Cpp\_SAXESwissSystem\cs8Tools\cs8Backup\cs8Backup.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile check
sub-cs8BackupSync-check:
	@if not exist cs8BackupSync\ mkdir cs8BackupSync\ & if not exist cs8BackupSync\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd cs8BackupSync\ && ( if not exist Makefile $(QMAKE) D:\data\Cpp\_SAXESwissSystem\cs8Tools\cs8BackupSync\cs8BackupSync.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile check
sub-cs8LogFileViewer-check:
	@if not exist cs8LogFileViewer\ mkdir cs8LogFileViewer\ & if not exist cs8LogFileViewer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd cs8LogFileViewer\ && ( if not exist Makefile $(QMAKE) D:\data\Cpp\_SAXESwissSystem\cs8Tools\cs8LogFileViewer\cs8LogFileViewer.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile check
sub-installer-check: sub-cs8Backup-check sub-cs8BackupSync-check sub-cs8LogFileViewer-check
	@if not exist installer\ mkdir installer\ & if not exist installer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd installer\ && ( if not exist Makefile $(QMAKE) D:\data\Cpp\_SAXESwissSystem\cs8Tools\installer\installer.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile check
check: sub-version-check sub-cs8Backup-check sub-cs8BackupSync-check sub-cs8LogFileViewer-check sub-installer-check

sub-version-benchmark:
	@if not exist version\ mkdir version\ & if not exist version\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd version\ && ( if not exist Makefile $(QMAKE) D:\data\Cpp\_SAXESwissSystem\cs8Tools\version\version.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile benchmark
sub-cs8Backup-benchmark:
	@if not exist cs8Backup\ mkdir cs8Backup\ & if not exist cs8Backup\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd cs8Backup\ && ( if not exist Makefile $(QMAKE) D:\data\Cpp\_SAXESwissSystem\cs8Tools\cs8Backup\cs8Backup.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile benchmark
sub-cs8BackupSync-benchmark:
	@if not exist cs8BackupSync\ mkdir cs8BackupSync\ & if not exist cs8BackupSync\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd cs8BackupSync\ && ( if not exist Makefile $(QMAKE) D:\data\Cpp\_SAXESwissSystem\cs8Tools\cs8BackupSync\cs8BackupSync.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile benchmark
sub-cs8LogFileViewer-benchmark:
	@if not exist cs8LogFileViewer\ mkdir cs8LogFileViewer\ & if not exist cs8LogFileViewer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd cs8LogFileViewer\ && ( if not exist Makefile $(QMAKE) D:\data\Cpp\_SAXESwissSystem\cs8Tools\cs8LogFileViewer\cs8LogFileViewer.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile benchmark
sub-installer-benchmark: sub-cs8Backup-benchmark sub-cs8BackupSync-benchmark sub-cs8LogFileViewer-benchmark
	@if not exist installer\ mkdir installer\ & if not exist installer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd installer\ && ( if not exist Makefile $(QMAKE) D:\data\Cpp\_SAXESwissSystem\cs8Tools\installer\installer.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile benchmark
benchmark: sub-version-benchmark sub-cs8Backup-benchmark sub-cs8BackupSync-benchmark sub-cs8LogFileViewer-benchmark sub-installer-benchmark
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

